[project]
name = "unitree-sdk2-python"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cyclonedds==0.10.2",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
]