[project]
name = "unitree_sdk2py"
version = "1.0.1"
dependencies = [
    "cyclonedds==0.10.2",
    "numpy",
    "opencv-python",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true